### ISSUE TITLE
sometimes it gives this error

### ISSUE THREAD

**Issue by mikiastilahun** [joelabair/multer-autoreap#20]
``` 
TypeError: path must be a string or Buffer
    at Object.fs.stat (fs.js:930:11)
    at processFile (/app/node_modules/multer-autoreap/index.js:23:6)
    at queue.forEach.file (/app/node_modules/multer-autoreap/index.js:57:5)
    at Array.forEach (<anonymous>)
    at Array.reapFiles (/app/node_modules/multer-autoreap/index.js:55:9)
    at listener (/app/node_modules/on-finished/index.js:169:15)
    at onFinish (/app/node_modules/on-finished/index.js:100:5)
    at callback (/app/node_modules/ee-first/index.js:55:10)
    at Socket.onevent (/app/node_modules/ee-first/index.js:93:5)
    at emitOne (events.js:121:20)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9) ```

**Comment by mikiastilahun** [comment]
Could anybody explain why the error keeps poping up
